import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {Header} from "@/components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Top 10 Searches",
  description: "Generated by Pyli",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >   <div>
        <Header />
        {/* <Link href={"/about"} > About</Link>
        <Link href={"/profile"} > Profile</Link>
        <Link href={"/wishlist"} > Wishlist</Link>
        <Link href={"/Bag"} > Bag</Link> */}
      </div>
        {children}
      </body>
    </html>
  );
}
